grep -rl 'Bayesian estimation' ./*.Rmd | xargs sed -i '/Bayesian estimation/ s/$/\\index{Bayesian estimation \/ 베이즈 추정}/' 
grep -rl 'Bayesian shrinkage' ./*.Rmd | xargs sed -i '/Bayesian shrinkage/ s/$/\\index{Bayesian shrinkage \/ 베이즈 축소추정}/' 
grep -rl 'between-subject variability, initerindividual variability(IIV)' ./*.Rmd | xargs sed -i '/between-subject variability, initerindividual variability(IIV)/ s/$/\\index{between-subject variability, initerindividual variability(IIV) \/ 개인간 변이}/' 
grep -rl 'binning' ./*.Rmd | xargs sed -i '/binning/ s/$/\\index{binning \/ 계급구간화}/' 
grep -rl 'bootstrapping' ./*.Rmd | xargs sed -i '/bootstrapping/ s/$/\\index{bootstrapping \/ 붓스트랩}/' 
grep -rl 'constant coefficient of variation' ./*.Rmd | xargs sed -i '/constant coefficient of variation/ s/$/\\index{constant coefficient of variation(CCV) \/ 고정변동계수(CCV)}/' 
grep -rl 'correlation coefficient' ./*.Rmd | xargs sed -i '/correlation coefficient/ s/$/\\index{correlation coefficient \/ 상관계수}/' 
grep -rl 'correlation matrix' ./*.Rmd | xargs sed -i '/correlation matrix/ s/$/\\index{correlation matrix \/ 상관행렬}/' 
grep -rl 'covariance' ./*.Rmd | xargs sed -i '/covariance/ s/$/\\index{covariance \/ 공분산}/' 
grep -rl 'diagonal matrix' ./*.Rmd | xargs sed -i '/diagonal matrix/ s/$/\\index{diagonal matrix \/ 대각행렬}/' 
grep -rl 'eigenvalues' ./*.Rmd | xargs sed -i '/eigenvalues/ s/$/\\index{eigenvalues \/ 고유값}/' 
grep -rl 'empirical Bayesian estimates' ./*.Rmd | xargs sed -i '/empirical Bayesian estimates/ s/$/\\index{empirical Bayesian estimates(EBE) \/ 경험적 베이즈 추정값(EBE)}/' 
grep -rl 'full covariate' ./*.Rmd | xargs sed -i '/full covariate/ s/$/\\index{full covariate \/ 모든 공변량}/' 
grep -rl 'gradient' ./*.Rmd | xargs sed -i '/gradient/ s/$/\\index{gradient \/ 기울기}/' 
grep -rl 'homoscedastic' ./*.Rmd | xargs sed -i '/homoscedastic/ s/$/\\index{homoscedastic \/ 등분산}/' 
grep -rl 'identifiability' ./*.Rmd | xargs sed -i '/identifiability/ s/$/\\index{identifiability \/ 식별가능성}/' 
grep -rl 'imputation' ./*.Rmd | xargs sed -i '/imputation/ s/$/\\index{imputation \/ 대체}/' 
grep -rl 'independent variable' ./*.Rmd | xargs sed -i '/independent variable/ s/$/\\index{independent variable \/ 독립변수}/' 
grep -rl 'indirect response model' ./*.Rmd | xargs sed -i '/indirect response model/ s/$/\\index{indirect response model \/ 간접효과모델}/' 
grep -rl 'individual parameter estimates' ./*.Rmd | xargs sed -i '/individual parameter estimates/ s/$/\\index{individual parameter estimates \/ 개인 파라미터 추정값}/' 
grep -rl 'individual residuals' ./*.Rmd | xargs sed -i '/individual residuals/ s/$/\\index{individual residuals \/ 개인 잔차}/' 
grep -rl 'individual(specific) prediction(s)' ./*.Rmd | xargs sed -i '/individual(specific) prediction(s)/ s/$/\\index{individual(specific) prediction(s) \/ 개인 예측}/' 
grep -rl 'internal validation' ./*.Rmd | xargs sed -i '/internal validation/ s/$/\\index{internal validation \/ 내부검증}/' 
grep -rl 'interoccasion variability' ./*.Rmd | xargs sed -i '/interoccasion variability/ s/$/\\index{interoccasion variability \/ 관찰시점간 변이}/' 
grep -rl 'intraindividual variability' ./*.Rmd | xargs sed -i '/intraindividual variability/ s/$/\\index{intraindividual variability \/ 개인내 변이}/' 
grep -rl 'iteration' ./*.Rmd | xargs sed -i '/iteration/ s/$/\\index{iteration \/ 되풀이}/' 
grep -rl 'likelihood' ./*.Rmd | xargs sed -i '/likelihood/ s/$/\\index{likelihood \/ 가능도}/' 
grep -rl 'likelihood ratio test' ./*.Rmd | xargs sed -i '/likelihood ratio test/ s/$/\\index{likelihood ratio test \/ 가능도비 검정}/' 
grep -rl 'local minimum' ./*.Rmd | xargs sed -i '/local minimum/ s/$/\\index{local minimum \/ 국소 최소값}/' 
grep -rl 'log-error (RV) model' ./*.Rmd | xargs sed -i '/log-error (RV) model/ s/$/\\index{log-error (RV) model \/ 로그 오차 모델}/' 
grep -rl 'logistic regression' ./*.Rmd | xargs sed -i '/logistic regression/ s/$/\\index{logistic regression \/ 로지스틱 회귀}/' 
grep -rl 'logit transform' ./*.Rmd | xargs sed -i '/logit transform/ s/$/\\index{logit transform \/ 로짓 변환}/' 
grep -rl 'log-likelihood profiling' ./*.Rmd | xargs sed -i '/log-likelihood profiling/ s/$/\\index{log-likelihood profiling \/ 로그 가능도 프로파일링}/' 
grep -rl 'minimum value of the objective function' ./*.Rmd | xargs sed -i '/minimum value of the objective function/ s/$/\\index{minimum value of the objective function \/ 목적함수(의) 최소값}/' 
grep -rl 'model diagnostic plots' ./*.Rmd | xargs sed -i '/model diagnostic plots/ s/$/\\index{model diagnostic plots \/ 모델 진단 플롯}/' 
grep -rl 'model misspecification' ./*.Rmd | xargs sed -i '/model misspecification/ s/$/\\index{model misspecification \/ 모델 오지정}/' 
grep -rl 'model specification file' ./*.Rmd | xargs sed -i '/model specification file/ s/$/\\index{model specification file \/ 모델 규격파일(MSF)}/' 
grep -rl 'nonpositive but semidefinite' ./*.Rmd | xargs sed -i '/nonpositive but semidefinite/ s/$/\\index{nonpositive but semidefinite \/ 양이 아니지만 준정부호}/' 
grep -rl 'numerical predictive check' ./*.Rmd | xargs sed -i '/numerical predictive check/ s/$/\\index{numerical predictive check(NPC) \/ 수치적 예측 점검(NPC)}/' 
grep -rl 'objective function' ./*.Rmd | xargs sed -i '/objective function/ s/$/\\index{objective function \/ 목적함수}/' 
grep -rl 'output files' ./*.Rmd | xargs sed -i '/output files/ s/$/\\index{output files \/ 실행결과 파일}/' 
grep -rl 'posterior predictive check' ./*.Rmd | xargs sed -i '/posterior predictive check/ s/$/\\index{posterior predictive check(PPC) \/ 사후예측점검(PPC)}/' 
grep -rl 'prior' ./*.Rmd | xargs sed -i '/prior/ s/$/\\index{prior \/ 사전 분포}/' 
grep -rl 'proportional error' ./*.Rmd | xargs sed -i '/proportional error/ s/$/\\index{proportional error \/ 비례오차}/' 
grep -rl 'relative bioavailability' ./*.Rmd | xargs sed -i '/relative bioavailability/ s/$/\\index{relative bioavailability \/ 상대 생체이용률}/' 
grep -rl 'rounding errors' ./*.Rmd | xargs sed -i '/rounding errors/ s/$/\\index{rounding errors \/ 반올림 오류}/' 
grep -rl 'seed value' ./*.Rmd | xargs sed -i '/seed value/ s/$/\\index{seed value \/ 시드값}/' 
grep -rl 'sequential fitting' ./*.Rmd | xargs sed -i '/sequential fitting/ s/$/\\index{sequential fitting \/ 순차적합법}/' 
grep -rl 'simulation' ./*.Rmd | xargs sed -i '/simulation/ s/$/\\index{simulation \/ 시뮬레이션}/' 
grep -rl 'simulatneous fitting' ./*.Rmd | xargs sed -i '/simulatneous fitting/ s/$/\\index{simulatneous fitting \/ 동시적합법}/' 
grep -rl 'time-dependent covariate, time-varying covariate' ./*.Rmd | xargs sed -i '/time-dependent covariate, time-varying covariate/ s/$/\\index{time-dependent covariate, time-varying covariate \/ 시간에 따라 변화하는 공변량}/' 
grep -rl 'variance-covariance matrix' ./*.Rmd | xargs sed -i '/variance-covariance matrix/ s/$/\\index{variance-covariance matrix \/ 분산-공분산 행렬}/' 
grep -rl 'visual predictive check' ./*.Rmd | xargs sed -i '/visual predictive check/ s/$/\\index{visual predictive check(VPC) \/ 시각적 예측 점검(VPC)}/' 
grep -rl 'weighting factor' ./*.Rmd | xargs sed -i '/weighting factor/ s/$/\\index{weighting factor(W) \/ 가중요소}/' 
grep -rl 'within-subject variability' ./*.Rmd | xargs sed -i '/within-subject variability/ s/$/\\index{within-subject variability \/ 개체내 변이}/' 
