cp "./docx/Chp 1_임동석.docx" "./zip/Chp 1_임동석.zip" 
cp "./docx/Chp 10 NONMEM OUTPUT_전상일_임동석 검토하고 수정완료.docx" "./zip/Chp 10 NONMEM OUTPUT_전상일_임동석 검토하고 수정완료.zip" 
cp "./docx/Chp 11 공변량 분석_한승훈.docx" "./zip/Chp 11 공변량 분석_한승훈.zip" 
cp "./docx/Chp 2  dataset_이소진_임동석검토_SJ.docx" "./zip/Chp 2  dataset_이소진_임동석검토_SJ.zip" 
cp "./docx/Chp 3 제어구문 소개_배수현_new_임동석검토.docx" "./zip/Chp 3 제어구문 소개_배수현_new_임동석검토.zip" 
cp "./docx/Chp 4 ADVAN1~4_전상일_임동석검토_최종본.docx" "./zip/Chp 4 ADVAN1~4_전상일_임동석검토_최종본.zip" 
cp "./docx/Chp 5 ADVAN5~8._홍태곤_임동석검토_TGH.docx" "./zip/Chp 5 ADVAN5~8._홍태곤_임동석검토_TGH.zip" 
cp "./docx/Chp 6 ADVAN9-13_임동석.docx" "./zip/Chp 6 ADVAN9-13_임동석.zip" 
cp "./docx/Chp 7 PRED_임동석.docx" "./zip/Chp 7 PRED_임동석.zip" 
cp "./docx/Chp 8 초기 값의 선택_한승훈.docx" "./zip/Chp 8 초기 값의 선택_한승훈.zip" 
cp "./docx/Chp 9 estimation method_김정렬_임동석검토_JRKim.docx" "./zip/Chp 9 estimation method_김정렬_임동석검토_JRKim.zip" 
