grep -rl 'scaling' ./*.Rmd | xargs sed -i '/scaling/ s/$/\\index{scaling parameter \/ 척도 파라미터}/' 
grep -rl 'standard error' ./*.Rmd | xargs sed -i '/standard error/ s/$/\\index{standard errors of the estimates \/ 추정값의 표준오차}/' 
grep -rl 'shrinkage' ./*.Rmd | xargs sed -i '/shrinkage/ s/$/\\index{shrinkage \/ 축소}/' 
grep -rl 'EDA' ./*.Rmd | xargs sed -i '/EDA/ s/$/\\index{exploratory data analysis(EDA) \/ 탐색적 데이터 분석(EDA)}/' 
grep -rl 'time after dose\|Time after dose' ./*.Rmd | xargs sed -i '/time after dose\|Time after dose/ s/$/\\index{time after dose \/ time after dose}/' 
grep -rl 'interdose interval' ./*.Rmd | xargs sed -i '/interdose interval/ s/$/\\index{interdose interval(II) \/ 투여간격}/' 
grep -rl 'specific ADVAN' ./*.Rmd | xargs sed -i '/specific ADVAN/ s/$/\\index{specific ADVANs \/ 특수 ADVAN}/' 
grep -rl 'indicator variable' ./*.Rmd | xargs sed -i '/indicator variable/ s/$/\\index{indicator variables \/ 표식 변수}/' 
grep -rl 'tolerance' ./*.Rmd | xargs sed -i '/tolerance/ s/$/\\index{tolerance \/ 허용치}/' 
grep -rl 'mixture model\|Mixture model' ./*.Rmd | xargs sed -i '/mixture model\|Mixture model/ s/$/\\index{mixture model \/ 혼합모델}/' 
grep -rl 'backward elimination\|Backward elimination' ./*.Rmd | xargs sed -i '/backward elimination\|Backward elimination/ s/$/\\index{backward elimination \/ 후진제거}/' 
grep -rl 'sparse data' ./*.Rmd | xargs sed -i '/sparse data/ s/$/\\index{sparse data \/ 희박자료}/' 
grep -rl 'FOCE' ./*.Rmd | xargs sed -i '/FOCE/ s/$/\\index{first-order conditional estimation method(FOCE) \/ 1차 조건부 추정방법(FOCE)}/' 
grep -rl 'FO \|first-order method' ./*.Rmd | xargs sed -i '/FO \|first-order method/ s/$/\\index{first-order method(FO) \/ 1차추정법}/' 
grep -rl 'first-order absorption' ./*.Rmd | xargs sed -i '/first-order absorption/ s/$/\\index{first-order absorption \/ 1차흡수}/' 
grep -rl 'two-stage approach' ./*.Rmd | xargs sed -i '/two-stage approach/ s/$/\\index{two-stage approach \/ 2단계 접근법}/' 
grep -rl 'FOCEI' ./*.Rmd | xargs sed -i '/FOCEI/ s/$/\\index{first-order conditional estimation with interaction(FOCEI) \/ INTERACTION 옵션을 쓰는 1차 조건부 추정방법(FOCEI)}/' 
grep -rl 'NM-TRAN' ./*.Rmd | xargs sed -i '/NM-TRAN/ s/$/\\index{NM-TRAN control stream \/ NM-TRAN 제어구문}/' 
grep -rl 'NONMEM report file' ./*.Rmd | xargs sed -i '/NONMEM report file/ s/$/\\index{NONMEM report file \/ NONMEM 보고 파일}/' 
grep -rl 'omega matrix' ./*.Rmd | xargs sed -i '/omega matrix/ s/$/\\index{omega matrix \/ OMEGA 행렬}/' 
grep -rl 'Q-Q plot' ./*.Rmd | xargs sed -i '/Q-Q plot/ s/$/\\index{Q-Q plot \/ Q-Q 플롯}/' 
grep -rl 'R matrix' ./*.Rmd | xargs sed -i '/R matrix/ s/$/\\index{R matrix \/ R 행렬}/' 
grep -rl 'S matrix' ./*.Rmd | xargs sed -i '/S matrix/ s/$/\\index{S matrix \/ S 행렬}/' 
grep -rl 'sigma matrix' ./*.Rmd | xargs sed -i '/sigma matrix/ s/$/\\index{sigma matrix \/ SIGMA 행렬}/' 
