grep -rl '사전 분포\|사전분포' ./*.Rmd | xargs sed -i '/사전 분포\|사전분포/ s/$/\\index{사전 분포 \/ prior}/' 
grep -rl '사후예측점검' ./*.Rmd | xargs sed -i '/사후예측점검/ s/$/\\index{사후예측점검(PPC) \/ posterior predictive check(PPC)}/' 
grep -rl '상관계수' ./*.Rmd | xargs sed -i '/상관계수/ s/$/\\index{상관계수 \/ correlation coefficient}/' 
grep -rl '상관행렬' ./*.Rmd | xargs sed -i '/상관행렬/ s/$/\\index{상관행렬 \/ correlation matrix}/' 
grep -rl '상대 생체이용률' ./*.Rmd | xargs sed -i '/상대 생체이용률/ s/$/\\index{상대 생체이용률 \/ relative bioavailability}/' 
grep -rl '수치적 예측 점검' ./*.Rmd | xargs sed -i '/수치적 예측 점검/ s/$/\\index{수치적 예측 점검(NPC) \/ numerical predictive check(NPC)}/' 
grep -rl '순차적합법' ./*.Rmd | xargs sed -i '/순차적합법/ s/$/\\index{순차적합법 \/ sequential fitting}/' 
grep -rl '시각적 예측 점검' ./*.Rmd | xargs sed -i '/시각적 예측 점검/ s/$/\\index{시각적 예측 점검(VPC) \/ visual predictive check(VPC)}/' 
grep -rl '시간에 따라 변화하는 공변량' ./*.Rmd | xargs sed -i '/시간에 따라 변화하는 공변량/ s/$/\\index{시간에 따라 변화하는 공변량 \/ time-dependent covariate, time-varying covariate}/' 
grep -rl '시뮬레이션' ./*.Rmd | xargs sed -i '/시뮬레이션/ s/$/\\index{시뮬레이션 \/ simulation}/' 
grep -rl '식별가능성' ./*.Rmd | xargs sed -i '/식별가능성/ s/$/\\index{식별가능성 \/ identifiability}/' 
grep -rl '실행결과 파일' ./*.Rmd | xargs sed -i '/실행결과 파일/ s/$/\\index{실행결과 파일 \/ output files}/' 
